<a href="https://colab.research.google.com/github/dohyeon-kim012/python-1./blob/main/5_20_%EC%98%A4%ED%9B%84%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [39]:
pop = pd.read_csv('/content/sample_data/pop.csv', header = 3, thousands=',')
pop

         기간    자치구      소계     남자     여자  ...   남자.6   여자.6   계.4  남자.7  여자.7
0   2021.03  서울특별시  151617  73389  78228  ...  29545  28887 -6216 -4453 -1763
1   2021.03    종로구    2644   1266   1378  ...    492    444   -53   -87    34
2   2021.03     중구    1966    949   1017  ...    365    352  -178  -126   -52
3   2021.03    용산구    4462   2111   2351  ...    668    674   580   169   411
4   2021.03    성동구    4656   2282   2374  ...    891    800  -385  -293   -92
5   2021.03    광진구    5432   2551   2881  ...   1050   1093  -395  -224  -171
6   2021.03   동대문구    5640   2802   2838  ...   1077   1007    96    36    60
7   2021.03    중랑구    5129   2534   2595  ...   1130   1043  -523  -326  -197
8   2021.03    성북구    6761   3180   3581  ...   1154   1162  -188  -206    18
9   2021.03    강북구    3802   1865   1937  ...    669    698  -484  -256  -228
10  2021.03    도봉구    3754   1831   1923  ...    775    777  -565  -291  -274
11  2021.03    노원구    6372   3075   3297  ...   1416   1301  -677  -404  -273
12  2021.03    은평구    6021   2859   3162  ...   1436   1425  -630  -372  -258
13  2021.03   서대문구    4930   2252   2678  ...    879    920  -160  -203    43
14  2021.03    마포구    6599   3104   3495  ...   1076   1158  -187   -58  -129
15  2021.03    양천구    6162   3048   3114  ...   1102    987  -240  -208   -32
16  2021.03    강서구    9737   4708   5029  ...   1903   1732   246   -25   271
17  2021.03    구로구    5175   2591   2584  ...   1263   1231  -246   -94  -152
18  2021.03    금천구    3388   1732   1656  ...    829    784   -52   -34   -18
19  2021.03   영등포구    6206   3027   3179  ...   1251   1190   -14  -102    88
20  2021.03    동작구    7245   3504   3741  ...   1248   1270   389   178   211
21  2021.03    관악구    9971   5001   4970  ...   2122   1991  -277  -192   -85
22  2021.03    서초구    6102   2914   3188  ...   1192   1190 -1025  -478  -547
23  2021.03    강남구    8868   4298   4570  ...   1634   1712 -1277  -656  -621
24  2021.03    송파구   10653   5079   5574  ...   2430   2496 -2090 -1151  -939
25  2021.03    강동구    9942   4826   5116  ...   1493   1450  2119   950  1169

[26 rows x 26 columns]

In [40]:
pop1 = pop.loc[1:,['자치구','남자','여자','남자.1','여자.1']]
pop1

     자치구    남자    여자  남자.1  여자.1
1    종로구  1266  1378  1353  1344
2     중구   949  1017  1075  1069
3    용산구  2111  2351  1942  1940
4    성동구  2282  2374  2575  2466
5    광진구  2551  2881  2775  3052
6   동대문구  2802  2838  2766  2778
7    중랑구  2534  2595  2860  2792
8    성북구  3180  3581  3386  3563
9    강북구  1865  1937  2121  2165
10   도봉구  1831  1923  2122  2197
11   노원구  3075  3297  3479  3570
12   은평구  2859  3162  3231  3420
13  서대문구  2252  2678  2455  2635
14   마포구  3104  3495  3162  3624
15   양천구  3048  3114  3256  3146
16   강서구  4708  5029  4733  4758
17   구로구  2591  2584  2685  2736
18   금천구  1732  1656  1766  1674
19  영등포구  3027  3179  3129  3091
20   동작구  3504  3741  3326  3530
21   관악구  5001  4970  5193  5055
22   서초구  2914  3188  3392  3735
23   강남구  4298  4570  4954  5191
24   송파구  5079  5574  6230  6513
25   강동구  4826  5116  3876  3947

In [43]:
pop1['총전입'] = pop1['남자'] + pop1['여자']
pop1['총전출'] = pop1['남자.1'] + pop1['여자.1']

In [52]:
pop1.columns = ['자치구','전입남자','전입여자','전출남자','전출여자','총전입','총전출']

In [53]:
pop1

     자치구  전입남자  전입여자  전출남자  전출여자    총전입    총전출
1    종로구  1266  1378  1353  1344   2644   2697
2     중구   949  1017  1075  1069   1966   2144
3    용산구  2111  2351  1942  1940   4462   3882
4    성동구  2282  2374  2575  2466   4656   5041
5    광진구  2551  2881  2775  3052   5432   5827
6   동대문구  2802  2838  2766  2778   5640   5544
7    중랑구  2534  2595  2860  2792   5129   5652
8    성북구  3180  3581  3386  3563   6761   6949
9    강북구  1865  1937  2121  2165   3802   4286
10   도봉구  1831  1923  2122  2197   3754   4319
11   노원구  3075  3297  3479  3570   6372   7049
12   은평구  2859  3162  3231  3420   6021   6651
13  서대문구  2252  2678  2455  2635   4930   5090
14   마포구  3104  3495  3162  3624   6599   6786
15   양천구  3048  3114  3256  3146   6162   6402
16   강서구  4708  5029  4733  4758   9737   9491
17   구로구  2591  2584  2685  2736   5175   5421
18   금천구  1732  1656  1766  1674   3388   3440
19  영등포구  3027  3179  3129  3091   6206   6220
20   동작구  3504  3741  3326  3530   7245   6856
21   관악구  5001  4970  5193  5055   9971  10248
22   서초구  2914  3188  3392  3735   6102   7127
23   강남구  4298  4570  4954  5191   8868  10145
24   송파구  5079  5574  6230  6513  10653  12743
25   강동구  4826  5116  3876  3947   9942   7823

In [55]:
pop2 = pop1.reindex( columns = ['자치구','전입남자','전입여자','총전입','전출남자','전출여자','총전출'])
pop2

     자치구  전입남자  전입여자    총전입  전출남자  전출여자    총전출
1    종로구  1266  1378   2644  1353  1344   2697
2     중구   949  1017   1966  1075  1069   2144
3    용산구  2111  2351   4462  1942  1940   3882
4    성동구  2282  2374   4656  2575  2466   5041
5    광진구  2551  2881   5432  2775  3052   5827
6   동대문구  2802  2838   5640  2766  2778   5544
7    중랑구  2534  2595   5129  2860  2792   5652
8    성북구  3180  3581   6761  3386  3563   6949
9    강북구  1865  1937   3802  2121  2165   4286
10   도봉구  1831  1923   3754  2122  2197   4319
11   노원구  3075  3297   6372  3479  3570   7049
12   은평구  2859  3162   6021  3231  3420   6651
13  서대문구  2252  2678   4930  2455  2635   5090
14   마포구  3104  3495   6599  3162  3624   6786
15   양천구  3048  3114   6162  3256  3146   6402
16   강서구  4708  5029   9737  4733  4758   9491
17   구로구  2591  2584   5175  2685  2736   5421
18   금천구  1732  1656   3388  1766  1674   3440
19  영등포구  3027  3179   6206  3129  3091   6220
20   동작구  3504  3741   7245  3326  3530   6856
21   관악구  5001  4970   9971  5193  5055  10248
22   서초구  2914  3188   6102  3392  3735   7127
23   강남구  4298  4570   8868  4954  5191  10145
24   송파구  5079  5574  10653  6230  6513  12743
25   강동구  4826  5116   9942  3876  3947   7823